//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSide.FoodTriviaServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FoodTriviaServiceReference.IFoodTriviaService")]
    public interface IFoodTriviaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodTriviaService/GetFoodTrivia", ReplyAction="http://tempuri.org/IFoodTriviaService/GetFoodTriviaResponse")]
        string GetFoodTrivia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodTriviaService/GetFoodTrivia", ReplyAction="http://tempuri.org/IFoodTriviaService/GetFoodTriviaResponse")]
        System.Threading.Tasks.Task<string> GetFoodTriviaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFoodTriviaServiceChannel : ClientSide.FoodTriviaServiceReference.IFoodTriviaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FoodTriviaServiceClient : System.ServiceModel.ClientBase<ClientSide.FoodTriviaServiceReference.IFoodTriviaService>, ClientSide.FoodTriviaServiceReference.IFoodTriviaService {
        
        public FoodTriviaServiceClient() {
        }
        
        public FoodTriviaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FoodTriviaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoodTriviaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoodTriviaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetFoodTrivia() {
            return base.Channel.GetFoodTrivia();
        }
        
        public System.Threading.Tasks.Task<string> GetFoodTriviaAsync() {
            return base.Channel.GetFoodTriviaAsync();
        }
    }
}
