//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSide.FoodJokeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FoodJokeServiceReference.IFoodJokeService1")]
    public interface IFoodJokeService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodJokeService1/GetFoodJoke", ReplyAction="http://tempuri.org/IFoodJokeService1/GetFoodJokeResponse")]
        string GetFoodJoke();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodJokeService1/GetFoodJoke", ReplyAction="http://tempuri.org/IFoodJokeService1/GetFoodJokeResponse")]
        System.Threading.Tasks.Task<string> GetFoodJokeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFoodJokeService1Channel : ClientSide.FoodJokeServiceReference.IFoodJokeService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FoodJokeService1Client : System.ServiceModel.ClientBase<ClientSide.FoodJokeServiceReference.IFoodJokeService1>, ClientSide.FoodJokeServiceReference.IFoodJokeService1 {
        
        public FoodJokeService1Client() {
        }
        
        public FoodJokeService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FoodJokeService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoodJokeService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoodJokeService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetFoodJoke() {
            return base.Channel.GetFoodJoke();
        }
        
        public System.Threading.Tasks.Task<string> GetFoodJokeAsync() {
            return base.Channel.GetFoodJokeAsync();
        }
    }
}
