//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public int Food_id { get; set; }
        public int Recipe_id { get; set; }
        public string Ingredient_name { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Unit { get; set; }
        public string image { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
