//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Ingredients = new HashSet<Ingredient>();
            this.users = new HashSet<user>();
        }
    
        public int Recipe_id { get; set; }
        public string Recipe_name { get; set; }
        public Nullable<int> Recipe_minutes { get; set; }
        public Nullable<byte> Recipe_veg { get; set; }
        public Nullable<byte> Recipe_vegan { get; set; }
        public Nullable<byte> cheap { get; set; }
        public Nullable<byte> sustainable { get; set; }
        public Nullable<byte> glutenfree { get; set; }
        public Nullable<byte> dairyfree { get; set; }
        public string image { get; set; }
        public string Instructions { get; set; }
        public string imageTyp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
