//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodService
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        public int User_id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<byte> gender { get; set; }
        public Nullable<byte> vegetarian { get; set; }
        public Nullable<byte> vegan { get; set; }
        public Nullable<byte> dairyfree { get; set; }
        public Nullable<byte> glutenfree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
